Ticket #1457: B check generated code script: ignore the '*.h_' files which are not commited
Avoid the following error since it is expected:
error: pathspec 'src/ClientServer/services/bgenc/constants_bs.h_' did not match any file(s) known to git.