Ticket #1387: Windows build script: detect incompatible options ENABLE_TESTING=1 / BUILD_SHARED_LIBS=1
It is not possible to build tests due to static references of encodeable types addresses leading to the following error type:
build\tests\ClientServer\test_server_address_space.c(51443): error C2099: l'initialiseur n'est pas une constante
build\tests\ClientServer\test_server_address_space.c(51445): warning C4047: 'initialisation' : les niveaux d'indirection de 'SOPC_EncodeableType *' et de 'int' sont différents